content:
  - name: posts
    label: Posts
    path: content/blog
    type: collection
    fields:
      - { name: published, label: Published, type: date, required: true }
      - { name: author, label: Autheur, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: cover, label: Couverture, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
media:
  input: public/img/content
  output: img/content
  categories: [image]