content:
  - name: posts
    label: Posts
    path: content/blog
    type: collection
    fields:
      - name: published
        label: Published
        type: date
        required: true
      - name: author
        label: Auteur
        type: string
        required: true
      - name: keywords
        label: Mots clef
        type: string
      - name: title
        label: Title
        type: string
        required: true
      - name: cover
        label: Couverture
        type: image
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
      - name: sitemap
        label: Sitemap
        type: object
        fields:
          - name: loc
            label: Loc
            type: string
          - name: lastmod
            label: Last modification
            type: date
          - name: changefreq
            label: Change freq
            type: select
            options:
              values:
              - value: always
                label: Always
              - value: hourly
                label: Hourly
              - value: daily
                label: Daily
              - value: weekly
                label: Weekly
              - value: monthly
                label: Monthly
              - value: yearly
                label: Yearly
              - value: never
                label: Never
          - name: priority
            label: Priority
            type: number
  - name: testimonials
    label: Recommandations
    path: content/testimonials
    type: collection
    fields:
      - name: author
        label: auteur
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Text
        type: rich-text
        required: true
  - name: services
    label: Services
    path: content/services
    type: collection
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: excerpt
        label: Resumé
        type: rich-text
        required: true
      - name: body
        label: Contenu
        type: rich-text
        required: true

        
media:
  input: public/img/content
  output: img/content
  categories: [image]