content:
  - name: posts
    label: Posts
    path: content/blog
    type: collection
    fields:
      - { name: published, label: Published, type: boolean }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }